# Generated by Django 4.0.2 on 2022-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='name',
            new_name='cast_name',
        ),
        migrations.AlterField(
            model_name='cast',
            name='movie',
            field=models.ManyToManyField(null=True, related_name='casts', to='movie.Movie'),
        ),
    ]
