# Generated by Django 4.0.2 on 2022-03-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_name_cast_cast_name_alter_cast_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='movie',
            new_name='movies',
        ),
    ]
